name: Quick Build

on: push

jobs:
  build:
    name: Quick build
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v0.0.3

# BUILD AND TEST
    - id: build-test
      name: Build and run tests
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          site

# TAR SITE
    - id: tar-site
      name: Tar generated site
      shell: bash
      run: |
        # Tar generated site
        tar -cvf ./generated-site.tar ./target/site

# UPLOAD GENERATED SITE
    - id: upload-generated-site
      name: Upload generated site with SchemaCrawler report
      uses: actions/upload-artifact@v2
      with:
        path: ./generated-site.tar
        name: generated-site
        retention-days: 5
